# Generated by Django 5.0.14 on 2026-07-03 20:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_claim_seller_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_purchase_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_types',
            field=models.JSONField(default=list, help_text='لیست روش\u200cهای پرداخت انتخابی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='superiors',
            field=models.ManyToManyField(blank=True, help_text='افراد بالادستی مستقیم این کاربر', related_name='subordinate_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateField(auto_now_add=True, default='2026-07-03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='branch',
            field=models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depositorder',
            name='branch',
            field=models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depositorder',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositorder',
            name='remaining_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemexit',
            name='branch',
            field=models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='branch',
            field=models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=15)),
                ('total_debt_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'پرداخت نشده'), ('IN_PROGRESS', 'در حال پیگیری'), ('NO_ANSWER', 'پاسخگو نیست'), ('REFUSED', 'عدم پرداخت'), ('PAID', 'پرداخت شده')], default='UNPAID', max_length=20)),
                ('taken_date', models.DateField(help_text='زمان بردن اجناس')),
                ('payment_deadline', models.DateField(help_text='مهلت خواسته شده برای پرداخت')),
                ('seller', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_up_type', models.CharField(choices=[('SMS', 'اس ام اسی'), ('PHONE', 'تلفنی'), ('IN_PERSON', 'حضوری'), ('OTHER', 'سایر')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.claim')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.claim')),
            ],
        ),
        migrations.CreateModel(
            name='DamageRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('branch', models.CharField(choices=[('شعبه بهشتی', 'شعبه بهشتی'), ('شعبه مدرس', 'شعبه مدرس'), ('شعبه سپیده', 'شعبه سپیده'), ('شعبه کاجستان', 'شعبه کاجستان')], max_length=50)),
                ('reason', models.CharField(choices=[('IRRIGATION', 'آبیاری'), ('PEST', 'آفت'), ('BREAKAGE', 'شکستگی'), ('LIGHT', 'نور'), ('OTHER', 'متفرقه'), ('UNKNOWN', 'نامعلوم')], max_length=20)),
                ('culprit', models.CharField(blank=True, help_text='مقصر', max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.damageregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=15)),
                ('action_type', models.CharField(choices=[('REFUND', 'فقط برگشت پول'), ('EXCHANGE', 'فقط تعویض کالا'), ('BOTH', 'هم برگشت پول هم تعویض کالا')], max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ برگشتی به مشتری', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید مدیریت'), ('APPROVED', 'تایید شده (در انتظار واریز)'), ('COMPLETED', 'تکمیل شده (واریز شده)'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('refund_date', models.DateField(blank=True, help_text='تاریخ واریز وجه', null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('CARD_TO_CARD', 'کارت به کارت'), ('ACCOUNT', 'حساب به حساب'), ('CHEQUE', 'چکی')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='core.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='core.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_items', to='core.returnrequest')),
            ],
        ),
    ]
