# Generated by Django 5.0.14 on 2026-07-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_new_roles_and_report_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdefinition',
            name='questions',
            field=models.JSONField(default=list, verbose_name='سوالات گزارش'),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='answers',
            field=models.JSONField(default=list, verbose_name='پاسخ\u200cها'),
        ),
    ]
