# Generated by Django 5.0.14 on 2026-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_branch_transfer_and_waste_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdefinition',
            name='interval',
            field=models.CharField(blank=True, choices=[('DAILY', 'روزانه'), ('WEEKLY', 'هفتگی'), ('MONTHLY', 'ماهانه'), ('BIMONTHLY', 'دو ماهه'), ('TRIMONTHLY', 'سه ماهه')], max_length=20, null=True, verbose_name='دوره تکرار'),
        ),
    ]
