# Generated by Django 5.0.14 on 2026-08-02 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_reportdefinition_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='اولین بازدید روز')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید روز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
