# Generated by Django 5.0.14 on 2026-08-02 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_useronlinelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ درخواستی')),
                ('description', models.TextField(verbose_name='توضیحات کاربر')),
                ('status', models.CharField(choices=[('PENDING_SUPERIOR', 'در انتظار تایید بالادستی'), ('REJECTED_BY_SUPERIOR', 'رد شده توسط بالادستی'), ('PENDING_ADMIN', 'در انتظار تایید ادمین'), ('REJECTED_BY_ADMIN', 'رد شده توسط ادمین'), ('PENDING_FINANCE', 'در انتظار پرداخت (مدیر مالی)'), ('PAID', 'پرداخت شده')], default='PENDING_SUPERIOR', max_length=30, verbose_name='وضعیت')),
                ('superior_note', models.TextField(blank=True, null=True, verbose_name='توضیحات بالادستی')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='توضیحات ادمین')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('finance_note', models.TextField(blank=True, null=True, verbose_name='توضیحات مدیر مالی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advances_as_admin', to=settings.AUTH_USER_MODEL)),
                ('finance_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_advances_as_finance', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('superior_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advances_as_superior', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, verbose_name='عملیات انجام شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('advance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.advancerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
