# Generated by Django 5.0.14 on 2026-08-06 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_advance_request_target_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='target_superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_advance_requests', to=settings.AUTH_USER_MODEL, verbose_name='بالادستی انتخاب\u200cشده'),
        ),
    ]
