# Generated by Django 5.0.14 on 2026-09-20 19:32

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seller_commission_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('PETTY_CASH', 'تنخواه'), ('PROFIT', 'سود')], max_length=20, verbose_name='نوع کارت')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'واریز / پرداخت به کارت'), ('WITHDRAWAL', 'برداشت / خرج از کارت')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاریخ تراکنش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidity_card_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'تراکنش کارت نقدینگی',
                'verbose_name_plural': 'تراکنش\u200cهای کارت\u200cهای نقدینگی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityDailyRevenueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='میزان درآمد روزانه (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_revenue_updates', to=settings.AUTH_USER_MODEL, verbose_name='به\u200cروزرسانی توسط')),
            ],
            options={
                'verbose_name': 'تنظیم درآمد روزانه نقدینگی',
                'verbose_name_plural': 'تنظیمات درآمد روزانه نقدینگی',
            },
        ),
        migrations.CreateModel(
            name='LiquidityExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='نام/عنوان هزینه')),
                ('category', models.CharField(choices=[('SALARY', 'حقوق'), ('DAILY', 'روزانه'), ('RENT', 'اجاره'), ('BILL', 'قبض'), ('CHEQUE', 'چک'), ('PURCHASE', 'خرید'), ('MISC', 'متفرقه')], default='MISC', max_length=30, verbose_name='دسته\u200cبندی')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ کل هزینه')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_paid', models.BooleanField(default=False, verbose_name='آیا تایید پرداخت زده شده است؟')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید نهایی پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidity_expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'هزینه نقدینگی',
                'verbose_name_plural': 'هزینه\u200cهای نقدینگی',
                'ordering': ['is_paid', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ پرداختی/تخصیص')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاریخ تخصیص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidity_payments_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.liquidityexpense', verbose_name='هزینه مربوطه')),
            ],
            options={
                'verbose_name': 'پرداخت/تخصیص هزینه نقدینگی',
                'verbose_name_plural': 'پرداخت\u200cهای هزینه\u200cهای نقدینگی',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
