# Generated by Django 5.0.14 on 2026-10-03 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_liquiditycardtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityDailyCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ شارژ روزانه (تومان)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات / بابت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ثبت شارژ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidity_daily_charges', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'شارژ روزانه نقدینگی',
                'verbose_name_plural': 'شارژهای روزانه نقدینگی',
                'ordering': ['-created_at'],
            },
        ),
    ]
