# Generated by Django 5.0.14 on 2026-10-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_liquidity_daily_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditycardtransaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='core.liquidityexpense', verbose_name='هزینه مربوطه (در صورت کسر خودکار)'),
        ),
        migrations.AlterField(
            model_name='liquiditycardtransaction',
            name='card_type',
            field=models.CharField(choices=[('SUPPLIER', 'تامین کننده'), ('SALARY', 'حقوق'), ('RENT', 'اجاره'), ('INSTALLMENTS', 'اقساط'), ('OTHER_EXPENSES', 'سایر هزینه ها'), ('MANAGEMENT', 'مدیریت'), ('SAVINGS', 'پس انداز'), ('CHARITY', 'خیریه'), ('EQUIPMENT', 'تجهیزات')], max_length=30, verbose_name='نوع کارت'),
        ),
        migrations.AlterField(
            model_name='liquidityexpense',
            name='category',
            field=models.CharField(choices=[('SUPPLIER', 'تامین کننده'), ('SALARY', 'حقوق'), ('RENT', 'اجاره'), ('INSTALLMENTS', 'اقساط'), ('OTHER_EXPENSES', 'سایر هزینه ها'), ('MANAGEMENT', 'مدیریت'), ('SAVINGS', 'پس انداز'), ('CHARITY', 'خیریه'), ('EQUIPMENT', 'تجهیزات')], default='OTHER_EXPENSES', max_length=30, verbose_name='دسته\u200cبندی'),
        ),
    ]
