# Generated by Django 5.0.14 on 2026-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_liquiditycardtransaction_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquiditycardtransaction',
            name='card_type',
            field=models.CharField(choices=[('SUPPLIER', 'کارت تامین کننده'), ('SALARY', 'کارت حقوق'), ('RENT', 'کارت اجاره'), ('INSTALLMENTS', 'کارت اقساط'), ('OTHER_EXPENSES', 'کارت سایر هزینه ها'), ('MANAGEMENT', 'کارت مدیریت'), ('SAVINGS', 'کارت پس انداز'), ('CHARITY', 'کارت خیریه'), ('EQUIPMENT', 'کارت تجهیزات')], max_length=30, verbose_name='نوع کارت'),
        ),
    ]
