# Generated by Django 5.0.14 on 2026-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_liquiditycardtransaction_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='آیا حذف شده است؟'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='original_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کاربری اولیه'),
        ),
    ]
